### ISSUE TITLE
add license to documentation

### ISSUE THREAD

**Issue by tomkralidis** [ZOO-Project/ZOO-Project#33]
In the context of OSGeo incubation, suggest to add a license for documentation (see pygeoapi for an example https://github.com/geopython/pygeoapi/blob/master/docs/source/conf.py#L98-L101)

**Comment by gfenoy** [comment]
The documentation license is here: https://zoo-project.github.io/docs/contribute/howto.html#licensing

**Comment by gfenoy** [comment]
Done in [0a265d1](https://github.com/ZOO-Project/ZOO-Project/commit/0a265d1249a49c05da80109b4c2159e2626ebf89).
