### ISSUE TITLE
clarify licenses

### ISSUE THREAD

**Issue by tomkralidis** [ZOO-Project/ZOO-Project#34]
According to https://github.com/ZOO-Project/ZOO-Project/wiki/OSGeoIncubation#9-which-open-source-licenses-will-the-source-code-be-released-under, there are 3 licenses.  Is this the current status?

**Comment by gfenoy** [comment]
We have added the documentation license.

**Comment by tomkralidis** [comment]
Thanks. Will continue docs license in #33

**Comment by gfenoy** [comment]
As the issue #33 is now closed. Should this issue also be?

**Comment by gfenoy** [comment]
We have made the following updates in the documentation to clarify the Licensing of the ZOO-Project:

 * https://github.com/ZOO-Project/ZOO-Project/blob/main/docs/intro.rst#open-source
 * https://github.com/ZOO-Project/ZOO-Project/blob/main/docs/contribute/howto.rst#licensing

We think that we add more clarity to the project licensing.

**Comment by tomkralidis** [comment]
2023-04-26 notes based on meeting with @gfenoy:

- current license files:
  - ZOO kernel: https://github.com/ZOO-Project/ZOO-Project/blob/main/LICENSE.md
  - all ZOO components: https://github.com/ZOO-Project/ZOO-Project/blob/main/zoo-project/LICENSE
- the ZOO kernel license at `LICENSE.md` facilitates license recognition when rendered by GitHub
- the all ZOO components license at `zoo-project/LICENSE` contains ALL licenses

**Comment by tomkralidis** [comment]
Implemented in https://github.com/ZOO-Project/ZOO-Project/wiki/ProjectGraduationChecklist#open
