### ISSUE TITLE
release procedures

### ISSUE THREAD

**Issue by tomkralidis** [ZOO-Project/ZOO-Project#35]
Does ZOO-Project release procedures, i.e. steps documented to work through a release process?

**Comment by gfenoy** [comment]
We have the following section in the official documentation https://zoo-project.github.io/docs/contribute/release.html

**Comment by tomkralidis** [comment]
Thanks. Added to https://github.com/ZOO-Project/ZOO-Project/wiki/ProjectGraduationChecklist
