### ISSUE TITLE
clarify support options

### ISSUE THREAD

**Issue by tomkralidis** [ZOO-Project/ZOO-Project#36]
Does ZOO-Project have a support page, which includes service providers/commercial options?

**Comment by gfenoy** [comment]
300619d8 introduced an initial service providers page.

**Comment by tomkralidis** [comment]
Thanks. Can you provide the resulting URL where this is available live?

**Comment by gfenoy** [comment]
The link to the produced documentation is here: https://zoo-project.github.io/docs/contribute/service_providers.html
