### ISSUE TITLE
provide list of known deployments or high profile projects

### ISSUE THREAD

**Issue by tomkralidis** [ZOO-Project/ZOO-Project#37]
To help with OSGeo incubation, provide a list of known deployments or high profile projects.

**Comment by tomkralidis** [comment]
2023-04-26 notes based on meeting with @gfenoy:

- provide 3-4 examples of known deployments on a wiki page (example: https://github.com/geopython/pygeoapi/wiki/LiveDeployments)
- if URLs are private/hidden/secure, then name of deployment is fine
- add to Graduation Checklist thereafter

**Comment by gfenoy** [comment]
I have create the following page: https://github.com/ZOO-Project/ZOO-Project/wiki/References

If it is enough, please let me know.

**Comment by tomkralidis** [comment]
Thanks @gfenoy.  This is fine.  Added to https://github.com/ZOO-Project/ZOO-Project/wiki/ProjectGraduationChecklist, thanks!
