### ISSUE TITLE
update contributor and license agreements

### ISSUE THREAD

**Issue by tomkralidis** [ZOO-Project/ZOO-Project#39]
As part of OSGeo Incubation, update and confirm copyright agreements (example: https://github.com/geopython/pygeoapi/issues/928)

**Comment by gfenoy** [comment]
Should we repeat the same thing that we made back in 2013?

https://lists.osgeo.org/pipermail/zoo-discuss/2013-July/000970.html

**Comment by tomkralidis** [comment]
We see 9 committers on [that page](http://zoo-project.org/docs/community/developper.html).  Here we see [13 contributors](https://github.com/ZOO-Project/ZOO-Project/graphs/contributors).  Suggest to provide a full list and have all contributors past and present agree to the guidelines.

**Comment by tomkralidis** [comment]
Process bootstrapped in #40.  @gfenoy I would also suggest a CLA as part of a PR template by default, for future contributors (see [example](https://github.com/geopython/pygeoapi/blob/master/.github/PULL_REQUEST_TEMPLATE.md)).

**Comment by gfenoy** [comment]
CLA has been added following your recommandation.

**Comment by tomkralidis** [comment]
2023-04-26 notes based on meeting with @gfenoy:

- PR CLA added in https://github.com/ZOO-Project/ZOO-Project/blob/main/.github/PULL_REQUEST_TEMPLATE.md
