### ISSUE TITLE
Debugging Error while running ETS ogcapi-processes-1.0

### ISSUE THREAD

**Issue by Koushikey4596** [ZOO-Project/ZOO-Project#53]
The following steps can be considered to find the issues while running  ETS ogcapi-processes-1.0:

1. Copy the failed test name and search the test module in the local directory. For ex. If we have error for test Job Results Exception Results Not Ready, we can search the file and error line number using command: grep test Job Results Exception Results Not Ready -rni ./
2. To debug, we add System.out.println("Error Message"). For ex, in my case it was "C:\Users\hp\ets-ogcapi-processes10\src\main\java\org\opengis\cite\ogcapiprocesses10\jobs.java". 
3. Modify the jobs.java and copy the modified source code in the docker folder. (For ex. C:\Users\hp\ZOO-Project\docker\ets-ogcapi-processes\src1\ets-ogcapi-processes10\src\main\java\org\opengis\cite\ogcapiprocesses10\jobs)
4. Build the docker using the command 'docker build . -f docker/ets-ogcapi-processes/Dockerfile --progress plain -t zooproject/ets-ogcapi-processes10:latest'.
5. run ‘docker-compose up -d’.
6. run ‘docker-compose logs zookernel’.
7. run ‘docker-compose logs teamengine --follow’ to view the real-time logs.

We can see the messages printed and thus can know exactly where the error is and thus can be rectified. 
![image](https://github.com/ZOO-Project/ZOO-Project/assets/20350988/d560715d-1c77-495a-b408-be63ba2e5b5f)

#https://github.com/opengeospatial/ets-ogcapi-processes10/issues/51

**Comment by gfenoy** [comment]
We can now close this issue.

Side-notes: there is a new ETS version that shows the request that has been sent and the result the ETS gets in case of failure. This a great enhancement.
