### ISSUE TITLE
Logs on the console for asynchrone processing for Docker environement

### ISSUE THREAD

**Issue by superptitsam** [ZOO-Project/ZOO-Project#65]
Currently the process of requests asynchronously will be managed by the FPM. But in such a case, the executions logs of the service are written inside a dedicated file for each execution.

I need to run Zoo-Project inside a Docker environment where the troubleshooting will be performed through a tool that is expecting for logs on the stdout/stderr. I'd like to have the possibility to configure that the logs are not written in a file but written on the stderr flow.

A possible solution would to create a new configuration entry in the main.cfg that will have the following way of working:
- By default if not present, the default logging process is kept
- if set with value "file", the default logging process is kept
- if set with value "console", the freopen function (inside zoo_service_loader.c) is not executed for stderr

If somebody thinks it can be a good idea, I can propose a Pull request

**Comment by gfenoy** [comment]
Actually, the ZOO-FPM is redirecting the stderr to a log file cause we don't have any way to get the debug messages from anywhere if they are printed on stderr. Indeed, from the ZOO-Kernel there is not such an issue because it runs from a web server, so the error messages can be accessed from the web server error log.

We can use the /var/log/zoofpm.log that is created at runtime to gather the error messages. The only issue I see with that is the fact that in case we have two services running at the same time then, their messages will be mixed together and it may make the debugging work harder than having the separated log files (one for each asynchronous execution).

Nevertheless, as it is an option that can be activated an deactivated at runtime, I am in favour of reviewing the PR you will propose for this new option.

**Comment by gfenoy** [comment]
@superptitsam may I ask what is your final decision on this?

**Comment by superptitsam** [comment]
Hello @gfenoy.  Yes of course you can ask ;-).
Finally, it appears that it could be too difficult due to internal processes to deploy a Rabbit MQ .... so we will kept the current deployement without FPM and RabbitMQ.
But the need to log the asynchronous services directly on the console is still here because we have to move to a Docker deployment with an internal tool that is waiting for console logs.

It takes me time to prepare the PR because your remark on the difficulties having all logs of parallel executions is something that already exist on our use of ZOO-Project. Finally since we have use Python services, I have decided to log the job-id for each line to let use debug. If you want, I can share an example of python script that use structlog to do such logging.

You will see that I have decided to move to a compilation parameter and not a configuration parameter to ensure that the produced Kernel will always log on the console accross all our environments but also to avoid a lot of test on this configuration parameter

**Comment by superptitsam** [comment]
Hello @gfenoy , do you have time to look to my PR linked to this issue?

**Comment by gfenoy** [comment]
Hello @superptitsam can you please explain why the service_json.c now requires to get gdal.h included? 

I don't understand this modification. If there is a valid justification then I can merge the PR.

**Comment by superptitsam** [comment]
Hello @gfenoy, I included the gdal.h because I was using a combinaison of argument to the build that cause compilation error due to missing variable TRUE. So I added gdal.h that include such variable.
But for our needs, I have changed the arguments and I don't face anymore the issue. So since I can not reproduce the issue, I have pushed a new commit to remove the include of gdal.h.

**Comment by sabarre** [comment]
Hello @gfenoy, sorry I had to work on other stuff on last months that explains no news from my side. 
Can you give me a feedback on my pull request?

**Comment by gfenoy** [comment]
> Hello @gfenoy, I included the gdal.h because I was using a combinaison of argument to the build that cause compilation error due to missing variable TRUE. So I added gdal.h that include such variable. But for our needs, I have changed the arguments and I don't face anymore the issue. So since I can not reproduce the issue, I have pushed a new commit to remove the include of gdal.h.

I am coming back on this as yesterday I faced the same kind of issue where `FALSE` was not defined (see. [ref](https://github.com/ZOO-Project/ZOO-Project/actions/runs/7885139544/job/21515603660#step:6:3666)).

I included the `service_internal_ms.h` from `service_callbacks.c` when `USE_MS` or `USE_CALLBACKS` is defined. This solved the issue.


> Hello @gfenoy, sorry I had to work on other stuff on last months that explains no news from my side. Can you give me a feedback on my pull request?

We added the `_fetchService` and `fetchService` functions. In the first function, we do allocate memory for `tmps1` (cf. [ref](https://github.com/ZOO-Project/ZOO-Project/blob/main/zoo-project/zoo-kernel/zoo_service_loader.c#L808)). From the second we use an array. Can you review this part of your pull request (PR)?

Reviewing the part mentioned should solve the conflict in the PR.

As we plan to have a release by the end of the week, it would be nice to merge this PR before the coming Saturday, meaning before the release candidate is made public.

**Comment by sabarre** [comment]
@gfenoy I have recreated a new Pull request correcsponding to the issue : https://github.com/ZOO-Project/ZOO-Project/pull/80

With the support of the logs on the console, I have also add some changes to the calls to the function fetchService in order yake account of the configuration parameter "servicePath".

**Comment by sabarre** [comment]
Hello @gfenoy , I see that a 2.0.0-RC1 has been released last week but my PR has not yet been merged. 
In order to move to a docker infrastructure, we need to generate our logs on the console so we need this PR.
Is my PR is still candidate to be part of the next general release?

**Comment by gfenoy** [comment]
@sabarre, I would be happy to have the PR integrated into the upcoming release. I have [commented](https://github.com/ZOO-Project/ZOO-Project/pull/80/files/9457c91e00cb559aea3613c699eebfee6181a400#diff-98d88740b893aed1ee9fbe19e1fca03d7c02887a56a2066cca453569d38931ad) before releasing RC1, thinking that we can revert the part I indicated or clarify what it implies (I ask because in our testing it does not cause any issue that we identified).

**Comment by sabarre** [comment]
Sorry @gfenoy but I don't see any comment on the llink you have mentioned.

**Comment by gfenoy** [comment]
Hi @sabarre, I guess it was a mistake on my side. I was sure that when I commented on the PR it would be visible to all. We can see a [comment](https://github.com/ZOO-Project/ZOO-Project/pull/80#discussion_r1493355418) that is available for 5 days...

Anyway, I went to the end and submited my review to ensure you an find it.

I wish we can solve this shortly.

**Comment by gfenoy** [comment]
Hi @sabarre, I think we can close this issue as your PR was integrated before publishing the release candidate 2 on Saturday, 24 February.

In case you need to, please reopen or open another issue.

**Comment by sabarre** [comment]
Hello @gfenoy, great! Thanks a lot for your support!
